# Preparing the database for regressions in Stata
library(tidyverse)
library(readxl)
library(reshape2)
library(dplyr)
library(matlab)
library(foreign)
library(stringi)

load("data/rdata/wiod_euk_ae_at.rdata") # generated by produc_hassler_cap.R
load("data/rdata/iea_pol_ind_feb2025.RData") # generated by import_IEA_ind_feb2025.R

# First get 2005 averages
industry_avgs_2005 <- wiod_euk_cap %>%
  filter(year == 2005) %>%
  group_by(ind) %>%
  summarise(avr_emissions_2005 = log(mean(x2_total, na.rm = TRUE)))

# Then join with main calculation
df <- wiod_euk_cap %>%
  group_by(COU, ind) %>%
  mutate(epg = log(ae)-lag(log(ae)),
         atg = log(at)-lag(log(at)),
         atg_stock = log(at_stock)-lag(log(at_stock))) %>%
  ungroup() %>%
  left_join(industry_avgs_2005, by = "ind") %>%
  group_by(year, ind) %>%
  mutate(avr_ep = mean(ae, na.rm = TRUE)) %>%
  group_by(year) %>%
  mutate(med_avr_ep = median(avr_ep, na.rm = TRUE),
         perc_75_ep = quantile(avr_ep, 0.75, na.rm = TRUE),
         perc_90_ep = quantile(avr_ep, 0.9, na.rm = TRUE)) %>%
  mutate(high_ep_2005 = ifelse(year == 2005 & avr_ep > med_avr_ep, 1, 0),
         high_75_ep_2005 = ifelse(year == 2005 & avr_ep > perc_75_ep, 1, 0),
         high_90_ep_2005 = ifelse(year == 2005 & avr_ep > perc_90_ep, 1, 0)) %>%
  ungroup()


high_ep_ind <- df %>% select(ind, high_ep_2005, high_75_ep_2005, high_90_ep_2005, year) %>%
  filter(year == 2005) %>% select(-c(year))
high_ep_ind <- high_ep_ind[!duplicated(high_ep_ind$ind), ] #DON'T FORGET THIS COMMA INSIDE THE BRACKETS!!!!!!!

df <- df %>% select(-c(high_ep_2005, high_75_ep_2005, high_90_ep_2005))
df <- left_join(df, high_ep_ind, by = "ind")
# df <- df %>% select(-c(high_ep_2005.x)) %>%
#   rename(high_ep_2005 = high_ep_2005.y)

df <- df %>% mutate(COUyearind = paste(COU, year, ind, sep = "_"))


df <- left_join(df, iea_pol_ind, by = "COUyearind")

df_pol <- df[!duplicated(df$COUyearind),]
    
# Create the average emissions by year and industry (averages across countries)
df_pol <- df_pol %>%
  select(COU, ind, year, ae, at, epg, atg, atg_stock, high_ep_2005, high_75_ep_2005, high_90_ep_2005, iea_pol_count, avr_emissions_2005) %>%
  filter(!is.na(iea_pol_count))


save(df_pol, file = "data/rdata/df_pol_feb2025.RData")
write.dta(df_pol, "data/dta/df_pol_feb2025.dta")