# Calculate productivity as in Hassler et al. (2021) using WIOD and EU KLEMS data.

library(tidyverse)
library(dplyr)
library(ggplot2)

load("data/rdata/euk_emissions.Rdata") #generated by merged_emissions_euk.R

gamma <- 0.5
epsilon <- 0.02
  
euk_emissions <- euk_emissions %>%
  mutate(ep = va_euk_usd/emissions,
         ae = ep*((1/ep)/gamma)^(epsilon/epsilon/(epsilon-1)),
         at = lp*((1/lp)/(1-gamma))^(epsilon/epsilon/(epsilon-1)))

euk_emissions_plot <- euk_emissions %>%
  group_by(COU, year) %>%
  summarise(emissions = sum(emissions, na.rm = TRUE),
            va_euk_usd = sum(va_euk_usd, na.rm = TRUE),
            emp_h = sum(emp_h, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(COU) %>%
  mutate(lp = va_euk_usd/emp_h,
         ep = va_euk_usd/emissions,
         at = lp*((1/lp)/(1-gamma))^(epsilon/epsilon/(epsilon-1)),
         ae = ep*((1/ep)/gamma)^(epsilon/epsilon/(epsilon-1)),
         ae_norm = ae/ae[1],
         at_norm = at/at[1],
         ep_norm = ep/ep[1],
         lp_norm = lp/lp[1],
         year = as.integer(year)) %>%
  ungroup()


countries <- unique(euk_emissions_plot$COU)
plot_all_countries <- list()

# for(i in 1:length(countries)){
#   euk_emissions_plot_cur <- euk_emissions_plot %>%
#     filter(COU == countries[i])
#   plot_cur <- ggplot(euk_emissions_plot_cur, aes(x = year)) +
#     # Add the first line
#     geom_line(aes(y = ae_norm, group = 1), color = "blue") +
#     # Add the second line
#     geom_line(aes(y = lp_norm, group = 2), color = "red") +
#     # Optional: Add labels and a title
#     labs(
#       x = "year",
#       y = "productivity",
#       title = countries[i]) +
#     scale_color_manual(values = c('blue', 'red'),
#                      labels = c('AE', 'AT'))
#   plot_all_countries[[i]] <- plot_cur
# }

for(i in 1:length(countries)){
  euk_emissions_plot_cur <- euk_emissions_plot %>%
    filter(COU == countries[i])
  plot_cur <- ggplot(euk_emissions_plot_cur, aes(x = year)) + 
    geom_line(aes(y = ae_norm, color = 'AE')) +
    geom_line(aes(y = at_norm, color = 'AT')) +
    scale_x_continuous(name = "Year",
                       labels = scales::number_format(scale = 1, accuracy = 1)) + #this removes decimal places from the years.
    scale_y_continuous(name = "Productivity") +
    labs(color = "Line",
         title = countries[i]) +
    scale_color_manual(values = c('blue', 'red'),
                       labels = c('AE', 'AT'))
  plot_all_countries[[i]] <- plot_cur
}


